package: css_above_the_fold
version: '2.0.0-beta1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/css_above_the_fold

requires:
    redaxo: '^5.18.1'
    php: '>=8.1'

default_config:
    active: true
    load_css_async: true
    debug: false
    preserve_important_rules: true
    include_css_vars: true
    breakpoints:
        xs: 375
        sm: 640
        md: 768
        lg: 1024
        xl: 1280
        xxl: 1536
    always_include_selectors: ":root\n.container\n.row"
    never_include_selectors: ".footer-\n.hidden"

page:
    title: 'translate:css_above_the_fold_title'
    perm: admin
    icon: rex-icon fa-rocket
    subpages:
        settings: { title: 'translate:settings' }
        cache: { title: 'translate:cache_management' }
