package: css_above_the_fold
version: '2.0.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/css_above_the_fold

requires:
    redaxo: '^5.18.1'
    php: '>=8.1'

default_config:
    active: true
    load_css_async: true
    breakpoints:
        xs: 375
        sm: 640
        md: 768
        lg: 1024
        xl: 1280
        xxl: 1536

page:
    title: 'CSS Above The Fold'
    perm: admin
    icon: rex-icon fa-css3
    subpages:
        settings: { title: 'translate:settings' }
